<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GAUTAM-PC" ignored="2" name="helperstest(failed)(failed)" tests="2" failures="2" timestamp="2019-12-17T10:40:27 IST" time="0.085" errors="0">
  <testcase name="testMethod3" time="0.016" classname="test.LoginTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at test.LoginTest.testMethod3(LoginTest.java:24)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase name="testMethod4" time="0.0" classname="test.LoginTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at test.LoginTest.testMethod4(LoginTest.java:31)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testMethod4 -->
  <testcase name="testMethod2" time="0.0" classname="test.LoginTest">
    <ignored/>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod1" time="0.0" classname="test.LoginTest">
    <ignored/>
  </testcase> <!-- testMethod1 -->
</testsuite> <!-- helperstest(failed)(failed) -->
